version: '3'
services:
  web:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Agbalagba21OK"
      POSTGRES_DB: "bicxchange"
    ports:
      - "5432:5432"

volumes:
  postgres_data:
